Feature/header
marinaghb/frontend-main pull request #1
Opened 2021-03-01 04:59 UTC by marinaghb

курсы Frontend, Спринт 1, Марина Почивалова

2021-03-03 07:11 UTC, studenttsu requested changes
Привет) Хорошая работа! Спасибо за форматирование кода, приятно читать.

Осталось поправить по одному комментарию и работа первого спринта будет принята!

Общая рекомендация - тестируй вёрстку на переполнение, при сильно больших изображенияй либо большому количеству текста, вёрстка не должна "ехать"

![image](https://user-images.githubusercontent.com/12005449/109767607-603ccc80-7c2a-11eb-95f7-5db982c16cce.png)

2021-03-03 07:11 UTC, studenttsu commented on index.html
> +                    <img src="./img/about_video_img.jpg" alt="Видео о нас">
`нужно поправить`

не хватает текстового содержание, картинку лучше сделать фоном
хочу обратить внимание, что затемнение фона нужно делать стилями, ведь сама картинка может быть любой

2021-03-03 07:11 UTC, studenttsu commented on index.html
> +                        <div class="img_container">
`можно лучше`

`img_container` - сильно общее название, хорошо бы подорать имя под сущность, которую описываешь. Выше у тебя есть обёртка с именем advantages

2021-03-03 07:11 UTC, studenttsu commented on index.html
> +                        <ul class="navigation">
`отлично`

круто, что переиспользуешь код

2021-03-06 16:09 UTC, marinaghb commented on index.html
> +                    <img src="./img/about_video_img.jpg" alt="Видео о нас">
Поправила. Картинку с кнопкой Play тоже сдеала фоном. Хотя там возможно должна быть ссылка... В общем,  пока так)

2021-03-06 16:10 UTC, marinaghb commented on index.html
> +                        <div class="img_container">
Исправила

2021-03-06 16:10 UTC, marinaghb commented on index.html
> +                        <ul class="navigation">
😊

2021-03-09 09:19 UTC, studenttsu approved these changes
Всё круто! Удачи в следующем спринте)

2021-03-09 09:35 UTC, merged