Sprint2
marinaghb/frontend-main pull request #2
Opened 2021-03-13 09:20 UTC by marinaghb

Задание для спринта2 (часть1).

2021-03-13 10:36 UTC, studenttsu requested changes
Хорошая работа! Нужно поправить важные моменты, описал в комментариях

2021-03-13 10:36 UTC, studenttsu commented on index.html
> +                            <img src="./img/popular_img.jpg" alt="Маникюр" class="pop-item__img">
Можно накинуть свойство `object-fit: cover;`, чтобы картинки другого размера и масштаба адекватно подстраивались под размер блока

2021-03-13 10:36 UTC, studenttsu commented on index.html
> +                            <button class="btn btn-small pop-item__btn">Записаться</button>
Не стоит забывать, что модификаторы имеются через нижнее подчёркивание
`.btn_small`

2021-03-13 10:36 UTC, studenttsu commented on index.html
> +                    <div class="master-card__foto master-card__foto-1"></div>
Картинки в этом случае нужно задавать через html

2021-03-14 07:38 UTC, marinaghb commented on index.html
> +                            <img src="./img/popular_img.jpg" alt="Маникюр" class="pop-item__img">
Добавила свойство. Спасибо за ревью! :)

2021-03-14 07:38 UTC, marinaghb commented on index.html
> +                            <button class="btn btn-small pop-item__btn">Записаться</button>
Исправила

2021-03-14 07:38 UTC, marinaghb commented on index.html
> +                    <div class="master-card__foto master-card__foto-1"></div>
Исправила

2021-03-15 04:39 UTC, studenttsu approved these changes
Удачи в работе след. спринта)

2021-03-15 05:03 UTC, merged

2021-03-15 05:04 UTC, marinaghb commented
> Удачи в работе след. спринта)

Спасибо :)